# Generated by Django 5.1.4 on 2024-12-19 10:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uo', '0002_alter_formation_responsable'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('CM', models.PositiveIntegerField()),
                ('TD', models.PositiveIntegerField()),
                ('TP', models.PositiveIntegerField()),
                ('credits', models.PositiveIntegerField()),
                ('formations', models.ManyToManyField(to='uo.formation')),
                ('responsables', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
